spring:
  datasource:
    url: jdbc:mysql://localhost:3306/homework
    username: root
    password: 000328
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    #    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    database: mysql
server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    sql: debug
    org:
      hibernate:
        SQL: debug
      springframework: debug
  pattern:
    console: "%red(%d{yyyy-MM-dd HH:mm:ss.SSS}) %green([%thread]) %blue([%-5level]) %cyan(%logger{36}:%line) %msg%n"