spring:
  datasource:
    url: jdbc:mysql://localhost:3306/homework?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: 000328
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
        initial-size: 5
        min-idle: 5
        max-active: 20
        max-wait: 60000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 1 FROM DUAL
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        web-stat-filter:
          enabled: true
          url-pattern: /*
          exclusions: /druid/*,*.js,*.css,*.gif,*.jpg,*.bmp,*.png,*.ico
        stat-view-servlet:
          enabled: true
          #访问德鲁伊监控页面的地址
          url-pattern: /druid/*
          #IP白名单 没有配置或者为空 则允许所有访问
          allow:
          #IP黑名单 若白名单也存在 则优先使用
          deny:
          #禁用重置按钮
          reset-enable: true
          #登录所用的用户名与密码
          login-username: admin
          login-password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    database: mysql
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: com_tc_zxy
        group: dev
      config:
        enabled: false
      username: nacos
      password: Nacos@#2022!
  application:
    name: SpringStudentService
server:
  port: 8088
  servlet:
    context-path: /
logging:
  level:
    sql: debug
    com:
      alibaba:
        druid: debug
    org:
      hibernate:
        SQL: debug
      springframework:
        web: debug
    springframework:
      data: debug
    root: info
  pattern:
    console: "%red(%d{yyyy-MM-dd HH:mm:ss.SSS}) %green([%thread]) %blue([%-5level]) %cyan(%logger{36}:%line) %msg%n"