spring:
  datasource:
    url: jdbc:mysql://localhost:3306/homework
    username: root
    password: 000328
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    database: mysql
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: com_tc_zxy
        group: dev
      config:
        enabled: false
  application:
    name: SpringStudentService
server:
  port: 8080
  servlet:
    context-path: /
logging:
  level:
    sql: debug
    org:
      hibernate:
        SQL: debug
      springframework:
        web: debug
  pattern:
    console: "%red(%d{yyyy-MM-dd HH:mm:ss.SSS}) %green([%thread]) %blue([%-5level]) %cyan(%logger{36}:%line) %msg%n"